import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";

// Load the font with desired weights and a CSS variable
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${poppins.variable} antialiased bg-[var(--primary-color)]`}
      >
        {children}
      </body>
    </html>
  );
}
